foreground #ffd5b2
background #000923
selection_foreground #000923
selection_background #1a2239

cursor #ffe0c5
cursor_text_color #000923

active_border_color #3f74ff
active_tab_background #3f74ff

color0 #000923
color1 #ff1720
color2 #1be33a
color3 #d9b800
color4 #3f74ff
color5 #f52e9b
color6 #00bea8
color7 #ffd5b2
color8 #3c6291
color9 #ff5155
color10 #3dff41
color11 #e4cc00
color12 #6695ff
color13 #ff69c1
color14 #10ffd9
color15 #ffe0c5
